name: compaexpress
description: "Aplicacion de facturacions simplificada"
publish_to: 'none'
version: 0.1.1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  amplify_flutter: ^2.0.0
  amplify_auth_cognito: ^2.0.0
  amplify_authenticator: ^2.0.0
  #amplify_datastore: ^2.0.0
  http: ^1.2.0
  dart_jsonwebtoken: ^2.12.0
  jwt_decoder: ^2.0.1
  amplify_api: ^2.0.0
  device_info_plus: ^11.5.0
  image_picker: ^1.0.0
  amplify_storage_s3: ^2.0.0
  flutter_native_splash: ^2.4.6
  simple_barcode_scanner: ^0.3.0
  package_info_plus: ^8.0.0
  universal_platform: ^1.1.0
  uuid: ^4.5.0
  connectivity_plus: ^6.0.0
  url_launcher: ^6.2.2
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.3
  fl_chart: ^0.68.0
  cached_network_image: ^3.3.0
  intl: ^0.20.2
  flutter_riverpod: ^3.0.3
  esc_pos_utils_plus: ^2.0.4
  flutter_thermal_printer: ^1.2.4
  print_bluetooth_thermal: ^1.1.7
  flutter_barcode_listener: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true
  assets:
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
flutter_native_splash:
  # Ruta de la imagen para el splash screen
  image: assets/splash.png
  # Color de fondo del splash screen (hexadecimal)
  color: "#009DFF"
  # Habilitar para Android
  android: true
  # Habilitar para iOS
  ios: true
  # Opcional: Color de fondo para modo oscuro
  color_dark: "#009DFF"